/*
  File autogenerated by gengetopt version 2.10
  generated with the following command:
  gengetopt -iinput.txt --conf-parser 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "getopt.h"

#include "cmdline.h"

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n"
  "Purpose:\n"
  "  stressnet is intended for replaying tcpdump/pcap capture files \n"
  "  -except the ethernet address- with a given bitrate to stress network \n"
  "  devices such as intrusion detection systems or firewalls.  It mixes two pcap\n"
  "  files (A and B) with a ratio r given as argument and meaning: for every 1 \n"
  "  packet of file B that is sent, there are r packets of file A that are sent. \n"
  "  This is meant to impose a rate of malformed packets in the dataflow.\n"
  "  \n"
  "  THIS SOFTWARE CAN AND SHOULD BE IMPROVED AS MUCH AS POSSIBLE, new ideas and \n"
  "  critics are always welcome.  You can send them by email to the following \n"
  "  address:\n"
  "  \n"
  "  \tyannick AT loth.be\n"
  "  \n"
  "  I would be pleased to discuss about them with you and to exchange ideas about\n"
  "  further improvements.\n"
  "  \n"
  "  This software was initially developed for the Royal Military Academy (RMA) of\n"
  "  Belgium (Brussels), by a student (Yannick Loth) during a training for his \n"
  "  studies as Industrial Engineer in Applied Informatics at the  University of \n"
  "  Luxembourg (2005).\n"
  "  The aim of stressnet is to provide a reliable tool (i.e. intended for \n"
  "  engineers etc.) to send packets (well formed and malformed ones) through a \n"
  "  network at different speeds and ratios of innofensive packets over attacking \n"
  "  packets to establish the limits of devices when they are seen as 'blackboxes',\n"
  "  i.e. when the internal functioning of the devices is unknown.\n"
  "  'Reliable' means that when someone asks for a certain bitrate, it should send\n"
  "  data at bitrates quite close to the wanted bitrate.\n"
  "  \n"
  "  The author of this software thanks Maj. W. Mees (RMA) and Capt. O. Thonnard \n"
  "  (RMA) as well as Pr. Th. Engel (Uni. Lux.) for their advices.\n"
  "  \n"
  "  stressnet should only be used by people knowing what they do, this tool could \n"
  "  in fact block your computer for a long time if you don't take care of what you\n"
  "  do.\n"
  "  \n"
  "  You'll (one day, I hope...) find more about this program on \n"
  "  \thttp://www.loth.be/yannick/stressnet/index.html\n"
  "\n"
  "Usage: %s [OPTIONS]...\n", CMDLINE_PARSER_PACKAGE);
  printf("   -h         --help                Print help and exit\n");
  printf("   -V         --version             Print version and exit\n");
  printf("   -iSTRING   --interface=STRING    network device used to send packets (default='eth0')\n");
  printf("   -mSTRING   --packetfileM=STRING  First file of packets\n");
  printf("   -nSTRING   --packetfileN=STRING  Second file ofpackets\n");
  printf("   -rLONG     --ratio=LONG          ratio M/N: number of packets of file M for every 1 packet of file N (default='50')\n");
  printf("   -bLONG     --bitrate=LONG        desired send bitrate in kbit/s (default='100')\n");
  printf("   -cSTRING   --configfile=STRING   config file containing the command line arguments\n");
  printf("   -pINT      --priority=INT        scheduling priority value (default='0')\n");
  printf("   -qINT      --quantity=INT        total quantity of packets to send (default='100')\n");
  printf("   -dSTRING   --destMAC=STRING      destination MAC address for ALL packets (default='00:11:22:33:44:55')\n");
  printf("   -s         --stats               simply output stats, no packet generation\n");
}


static char *gengetopt_strdup (const char *s);

/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  int c;	/* Character of the parsed option.  */
  int missing_required_options = 0;

  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->interface_given = 0 ;
  args_info->packetfileM_given = 0 ;
  args_info->packetfileN_given = 0 ;
  args_info->ratio_given = 0 ;
  args_info->bitrate_given = 0 ;
  args_info->configfile_given = 0 ;
  args_info->priority_given = 0 ;
  args_info->quantity_given = 0 ;
  args_info->destMAC_given = 0 ;
  args_info->stats_given = 0 ;
#define clear_args() { \
  args_info->interface_arg = gengetopt_strdup("eth0") ;\
  args_info->packetfileM_arg = NULL; \
  args_info->packetfileN_arg = NULL; \
  args_info->ratio_arg = 50 ;\
  args_info->bitrate_arg = 100 ;\
  args_info->configfile_arg = NULL; \
  args_info->priority_arg = 0 ;\
  args_info->quantity_arg = 100 ;\
  args_info->destMAC_arg = gengetopt_strdup("00:11:22:33:44:55") ;\
}

  clear_args();

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "interface",	1, NULL, 'i' },
        { "packetfileM",	1, NULL, 'm' },
        { "packetfileN",	1, NULL, 'n' },
        { "ratio",	1, NULL, 'r' },
        { "bitrate",	1, NULL, 'b' },
        { "configfile",	1, NULL, 'c' },
        { "priority",	1, NULL, 'p' },
        { "quantity",	1, NULL, 'q' },
        { "destMAC",	1, NULL, 'd' },
        { "stats",	0, NULL, 's' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVi:m:n:r:b:c:p:q:d:s", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          clear_args ();
          cmdline_parser_print_help ();
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          clear_args ();
          cmdline_parser_print_version ();
          exit (EXIT_SUCCESS);

        case 'i':	/* network device used to send packets.  */
          if (args_info->interface_given)
            {
              fprintf (stderr, "%s: `--interface' (`-i') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->interface_given = 1;
          args_info->interface_arg = gengetopt_strdup (optarg);
          break;

        case 'm':	/* First file of packets.  */
          if (args_info->packetfileM_given)
            {
              fprintf (stderr, "%s: `--packetfileM' (`-m') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->packetfileM_given = 1;
          args_info->packetfileM_arg = gengetopt_strdup (optarg);
          break;

        case 'n':	/* Second file ofpackets.  */
          if (args_info->packetfileN_given)
            {
              fprintf (stderr, "%s: `--packetfileN' (`-n') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->packetfileN_given = 1;
          args_info->packetfileN_arg = gengetopt_strdup (optarg);
          break;

        case 'r':	/* ratio M/N: number of packets of file M for every 1 packet of file N.  */
          if (args_info->ratio_given)
            {
              fprintf (stderr, "%s: `--ratio' (`-r') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->ratio_given = 1;
          args_info->ratio_arg = strtol (optarg,&stop_char,0);
          break;

        case 'b':	/* desired send bitrate in kbit/s.  */
          if (args_info->bitrate_given)
            {
              fprintf (stderr, "%s: `--bitrate' (`-b') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->bitrate_given = 1;
          args_info->bitrate_arg = strtol (optarg,&stop_char,0);
          break;

        case 'c':	/* config file containing the command line arguments.  */
          if (args_info->configfile_given)
            {
              fprintf (stderr, "%s: `--configfile' (`-c') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->configfile_given = 1;
          args_info->configfile_arg = gengetopt_strdup (optarg);
          break;

        case 'p':	/* scheduling priority value.  */
          if (args_info->priority_given)
            {
              fprintf (stderr, "%s: `--priority' (`-p') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->priority_given = 1;
          args_info->priority_arg = strtol (optarg,&stop_char,0);
          break;

        case 'q':	/* total quantity of packets to send.  */
          if (args_info->quantity_given)
            {
              fprintf (stderr, "%s: `--quantity' (`-q') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->quantity_given = 1;
          args_info->quantity_arg = strtol (optarg,&stop_char,0);
          break;

        case 'd':	/* destination MAC address for ALL packets.  */
          if (args_info->destMAC_given)
            {
              fprintf (stderr, "%s: `--destMAC' (`-d') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->destMAC_given = 1;
          args_info->destMAC_arg = gengetopt_strdup (optarg);
          break;

        case 's':	/* simply output stats, no packet generation.  */
          if (args_info->stats_given)
            {
              fprintf (stderr, "%s: `--stats' (`-s') option given more than once\n", CMDLINE_PARSER_PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->stats_given = 1;
          break;


        case 0:	/* Long option with no short option */

        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          exit (EXIT_FAILURE);

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c\n", CMDLINE_PARSER_PACKAGE, c);
          abort ();
        } /* switch */
    } /* while */


  if (! args_info->packetfileM_given)
    {
      fprintf (stderr, "%s: '--packetfileM' ('-m') option required\n", CMDLINE_PARSER_PACKAGE);
      missing_required_options = 1;
    }
  if ( missing_required_options )
    exit (EXIT_FAILURE);

  return 0;
}

#define CONFIGPARSERBUFSIZE 1024

int
cmdline_parser_configfile (char * const filename, struct gengetopt_args_info *args_info, int override)
{
  FILE* file;
  char linebuf[CONFIGPARSERBUFSIZE];
  int line_num = 0;
  int len;
  int fnum;
  char fopt[CONFIGPARSERBUFSIZE], farg[CONFIGPARSERBUFSIZE];
  char *stop_char;
  char *str_index, *str_index2;
  int next_token;

  if ((file = fopen(filename, "r")) == NULL)
    {
      fprintf (stderr, "%s: Error opening configuration file '%s'\n",
               CMDLINE_PARSER_PACKAGE, filename);
      exit (EXIT_FAILURE);
    }

  while ((fgets(linebuf, CONFIGPARSERBUFSIZE, file)) != NULL)
    {
      ++line_num;
      len = strlen(linebuf);
      if (len == CONFIGPARSERBUFSIZE-1)
        {
          fprintf (stderr, "%s: Line longer than %d characters found in configuration file '%s'\n",
                   CMDLINE_PARSER_PACKAGE, CONFIGPARSERBUFSIZE, filename);
          exit (EXIT_FAILURE);
        }

      if (linebuf[0] == '#')
        continue; /* Line was a comment */

      /* read the option */
      fnum = sscanf (linebuf, "%s", fopt);

      if (fnum < 0)
        continue; /* blank line */

      next_token = strlen (fopt);
      str_index = strchr (&linebuf[next_token], '\"');
      if (str_index)
        {
          str_index2 = strchr (str_index + 1, '\"');
          if (! str_index2)
            {
              fprintf 
                (stderr, 
                 "%s: unterminated string in configuration file '%s'\n",
                 CMDLINE_PARSER_PACKAGE, filename);
              exit (EXIT_FAILURE);
            }

          strncpy (farg, str_index + 1, str_index2 - str_index - 1);
          farg[str_index2 - str_index]='\0';
          ++fnum;
        }
      else
        if (sscanf (&linebuf[next_token], "%s", farg) > 0)
          ++fnum;

      if (fnum > 0)
        {
          if (!strcmp(fopt, "help"))
            {
              if (override || !args_info->help_given)
                {
                  args_info->help_given = 1;
                  
                }
              continue;
            }
          if (!strcmp(fopt, "version"))
            {
              if (override || !args_info->version_given)
                {
                  args_info->version_given = 1;
                  
                }
              continue;
            }
          if (!strcmp(fopt, "interface"))
            {
              if (override || !args_info->interface_given)
                {
                  args_info->interface_given = 1;
                  if (fnum == 2)
                    args_info->interface_arg = gengetopt_strdup (farg);
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "packetfileM"))
            {
              if (override || !args_info->packetfileM_given)
                {
                  args_info->packetfileM_given = 1;
                  if (fnum == 2)
                    args_info->packetfileM_arg = gengetopt_strdup (farg);
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "packetfileN"))
            {
              if (override || !args_info->packetfileN_given)
                {
                  args_info->packetfileN_given = 1;
                  if (fnum == 2)
                    args_info->packetfileN_arg = gengetopt_strdup (farg);
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "ratio"))
            {
              if (override || !args_info->ratio_given)
                {
                  args_info->ratio_given = 1;
                  if (fnum == 2)
                    args_info->ratio_arg = strtol (farg,&stop_char,0);
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "bitrate"))
            {
              if (override || !args_info->bitrate_given)
                {
                  args_info->bitrate_given = 1;
                  if (fnum == 2)
                    args_info->bitrate_arg = strtol (farg,&stop_char,0);
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "configfile"))
            {
              if (override || !args_info->configfile_given)
                {
                  args_info->configfile_given = 1;
                  if (fnum == 2)
                    args_info->configfile_arg = gengetopt_strdup (farg);
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "priority"))
            {
              if (override || !args_info->priority_given)
                {
                  args_info->priority_given = 1;
                  if (fnum == 2)
                    args_info->priority_arg = strtol (farg,&stop_char,0);
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "quantity"))
            {
              if (override || !args_info->quantity_given)
                {
                  args_info->quantity_given = 1;
                  if (fnum == 2)
                    args_info->quantity_arg = strtol (farg,&stop_char,0);
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "destMAC"))
            {
              if (override || !args_info->destMAC_given)
                {
                  args_info->destMAC_given = 1;
                  if (fnum == 2)
                    args_info->destMAC_arg = gengetopt_strdup (farg);
                  else
                    {
                      fprintf (stderr, "%s:%d: required <option_name> <option_val>\n",
                               filename, line_num);
                      exit (EXIT_FAILURE);
                    }
                }
              continue;
            }
          if (!strcmp(fopt, "stats"))
            {
              if (override || !args_info->stats_given)
                {
                  args_info->stats_given = 1;
                  
                }
              continue;
            }
          

          /* Tried all known options. This one is unknown! */
          fprintf (stderr, "%s: Unknown option '%s' found in %s\n",
                   CMDLINE_PARSER_PACKAGE, fopt, filename);
          exit (EXIT_FAILURE);
        }
    } /* while */
  fclose(file); /* No error checking on close */

  return 0;
}
